export const regioesAdministrativasDf = [
    { codigo: 1, nome: 'Plano Piloto', label: 'RA 1º - Plano Piloto', value: 'Plano Piloto' },
    { codigo: 2, nome: 'Gama', label: 'RA 2º - Gama', value: 'Gama' },
    { codigo: 3, nome: 'Taguatinga', label: 'RA 3º - Taguatinga', value: 'Taguatinga' },
    { codigo: 4, nome: 'Brazlândia', label: 'RA 4º - Brazlândia', value: 'Brazlândia' },
    { codigo: 5, nome: 'Sobradinho', label: 'RA 5º - Sobradinho', value: 'Sobradinho' },
    { codigo: 6, nome: 'Planaltina', label: 'RA 6º - Planaltina', value: 'Planaltina' },
    { codigo: 7, nome: 'Paranoá', label: 'RA 7º - Paranoá', value: 'Paranoá' },
    { codigo: 8, nome: 'Núcleo Bandeirante', label: 'RA 8º - Núcleo Bandeirante', value: 'Núcleo Bandeirante' },
    { codigo: 9, nome: 'Ceilândia', label: 'RA 9º - Ceilândia', value: 'Ceilândia' },
    { codigo: 10, nome: 'Guará', label: 'RA 10º - Guará', value: 'Guará' },
    { codigo: 11, nome: 'Cruzeiro', label: 'RA 11º - Cruzeiro', value: 'Cruzeiro' },
    { codigo: 12, nome: 'Samambaia', label: 'RA 12º - Samambaia', value: 'Samambaia' },
    { codigo: 13, nome: 'Santa Maria', label: 'RA 13º - Santa Maria', value: 'Santa Maria' },
    { codigo: 14, nome: 'São Sebastião', label: 'RA 14º - São Sebastião', value: 'São Sebastião' },
    { codigo: 15, nome: 'Recanto das Emas', label: 'RA 15º - Recanto das Emas', value: 'Recanto das Emas' },
    { codigo: 16, nome: 'Lago Sul', label: 'RA 16º - Lago Sul', value: 'Lago Sul' },
    { codigo: 17, nome: 'Riacho Fundo', label: 'RA 17º - Riacho Fundo', value: 'Riacho Fundo' },
    { codigo: 18, nome: 'Lago Norte', label: 'RA 18º - Lago Norte', value: 'Lago Norte' },
    { codigo: 19, nome: 'Candangolândia', label: 'RA 19º - Candangolândia', value: 'Candangolândia' },
    { codigo: 20, nome: 'Águas Claras', label: 'RA 20º - Águas Claras', value: 'Águas Claras' },
    { codigo: 21, nome: 'Riacho Fundo II', label: 'RA 21º - Riacho Fundo II', value: 'Riacho Fundo II' },
    { codigo: 22, nome: 'Sudoeste/Octogonal', label: 'RA 22º - Sudoeste/Octogonal', value: 'Sudoeste/Octogonal' },
    { codigo: 23, nome: 'Varjão', label: 'RA 23º - Varjão', value: 'Varjão' },
    { codigo: 24, nome: 'Park Way', label: 'RA 24º - Park Way', value: 'Park Way' },
    { codigo: 25, nome: 'SCIA / Estrutural', label: 'RA 25º - SCIA / Estrutural', value: 'SCIA / Estrutural' },
    { codigo: 26, nome: 'Sobradinho II', label: 'RA 26º - Sobradinho II', value: 'Sobradinho II' },
    { codigo: 27, nome: 'Jardim Botânico', label: 'RA 27º - Jardim Botânico', value: 'Jardim Botânico' },
    { codigo: 28, nome: 'Itapoã', label: 'RA 28º - Itapoã', value: 'Itapoã' },
    { codigo: 29, nome: 'SIA (Setor de Indústria e Abastecimento)', label: 'RA 29º - SIA (Setor de Indústria e Abastecimento)', value: 'SIA (Setor de Indústria e Abastecimento)' },
    { codigo: 30, nome: 'Vicente Pires', label: 'RA 30º - Vicente Pires', value: 'Vicente Pires' },
    { codigo: 31, nome: 'Fercal', label: 'RA 31º - Fercal', value: 'Fercal' },
    { codigo: 32, nome: 'Sol Nascente / Pôr do Sol', label: 'RA 32º - Sol Nascente / Pôr do Sol', value: 'Sol Nascente / Pôr do Sol' },
    { codigo: 33, nome: 'Arniqueira', label: 'RA 33º - Arniqueira', value: 'Arniqueira' },
    { codigo: 34, nome: 'Arapoanga', label: 'RA 34º - Arapoanga', value: 'Arapoanga' },
    { codigo: 35, nome: 'Água Quente', label: 'RA 35º - Água Quente', value: 'Água Quente' },
    { codigo: 36, nome: '26 de Setembro', label: 'RA 36º - 26 de Setembro', value: '26 de Setembro' },
    { codigo: 37, nome: 'Ponte Alta', label: 'RA 37º - Ponte Alta', value: 'Ponte Alta' },
];

export const regioesAdministrativasPermitidas = regioesAdministrativasDf.map((regiao) => regiao.value);
